### ISSUE TITLE
Intial Loadbalancing fails with latest merge

### ISSUE THREAD

**Issue by ahurta92** [m-a-d-n-e-s-s/madness#551] opened 2024-10-09 20:15 UTC
I believe the latest commits merging fix/fence-semantics introduced some bug that causes moldft to fail during `SCF::intial_load_balance` .    Below is the output where it fails.  I also have the picture of the stack.  I'm not sure what the issue is but I believe the problem is introduced through commit :6ab44846c4e2e603d24e731c5bd7f18cbf22fbaf "fence checks postcondition that there are no tasks".  
![image](https://github.com/user-attachments/assets/6ce274c4-6c28-42e1-8966-bd44b169e859)

```
timer:     Project vnuclear     0.09s     0.09s
[sn-mem:77080:0:77080] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
[sn-mem:77079:0:77079] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))

BFD: Dwarf Error: found dwarf version '5', this reader only handles version 2, 3 and 4 information.
==== backtrace (tid:  77080) ====
 0 0x000000000004d455 ucs_debug_print_backtrace()  ???:0
 1 0x0000000000156cb4 __memcpy_ssse3_back()  :0
 2 0x00000000004a8eaa madness::archive::BufferOutputArchive::store<unsigned long>()  ???:0
 3 0x00000000004a8937 madness::archive::default_serialize<madness::archive::BufferOutputArchive, unsigned long>()  ???:0
 4 0x00000000004a8415 madness::archive::default_serialize<madness::archive::BufferOutputArchive, unsigned long>()  ???:0
 5 0x00000000004a7b3b madness::archive::ArchiveStoreImpl<madness::archive::BufferOutputArchive, unsigned long, void>::store<madness::archive::BufferOutputArchive, unsigned long>()  ???:0
 6 0x00000000004a732b madness::archive::ArchiveImpl<madness::archive::BufferOutputArchive, unsigned long, void>::wrap_store<madness::archive::BufferOutputArchive, void>()  ???:0
 7 0x00000000004a6732 madness::archive::operator&<madness::archive::BufferOutputArchive, unsigned long>()  ???:0
 8 0x000000000057f73b madness::archive::ArchiveStoreImpl<madness::archive::BufferOutputArchive, std::vector<std::pair<madness::Key<3ul>, double>, std::allocator<std::pair<madness::Key<3ul>, double> > >, void>::store()  ???:0
 9 0x00000000005666a6 madness::archive::ArchiveImpl<madness::archive::BufferOutputArchive, std::vector<std::pair<madness::Key<3ul>, double>, std::allocator<std::pair<madness::Key<3ul>, double> > >, void>::wrap_store<madness::archive::BufferOutputArchive, void>()  ???:0
10 0x0000000000555034 madness::archive::operator&<madness::archive::BufferOutputArchive, std::vector<std::pair<madness::Key<3ul>, double>, std::allocator<std::pair<madness::Key<3ul>, double> > > >()  ???:0
11 0x000000000054537a madness::WorldGopInterface::concat0<std::pair<madness::Key<3ul>, double> >()  ???:0
12 0x0000000000535a95 madness::LoadBalanceDeux<3ul>::load_balance()  ???:0
13 0x0000000000514cb0 madness::SCF::initial_load_bal()  ???:0
14 0x0000000000437d9d main()  ???:0
15 0x0000000000022555 __libc_start_main()  ???:0
16 0x0000000000437129 _start()  ???:0
=================================
==== backtrace (tid:  77079) ====
 0 0x000000000004d455 ucs_debug_print_backtrace()  ???:0
 1 0x0000000000156cb4 __memcpy_ssse3_back()  :0
 2 0x00000000004a8eaa madness::archive::BufferOutputArchive::store<unsigned long>()  ???:0
 3 0x00000000004a8937 madness::archive::default_serialize<madness::archive::BufferOutputArchive, unsigned long>()  ???:0
 4 0x00000000004a8415 madness::archive::default_serialize<madness::archive::BufferOutputArchive, unsigned long>()  ???:0
 5 0x00000000004a7b3b madness::archive::ArchiveStoreImpl<madness::archive::BufferOutputArchive, unsigned long, void>::store<madness::archive::BufferOutputArchive, unsigned long>()  ???:0
 6 0x00000000004a732b madness::archive::ArchiveImpl<madness::archive::BufferOutputArchive, unsigned long, void>::wrap_store<madness::archive::BufferOutputArchive, void>()  ???:0
 7 0x00000000004a6732 madness::archive::operator&<madness::archive::BufferOutputArchive, unsigned long>()  ???:0
 8 0x000000000057f73b madness::archive::ArchiveStoreImpl<madness::archive::BufferOutputArchive, std::vector<std::pair<madness::Key<3ul>, double>, std::allocator<std::pair<madness::Key<3ul>, double> > >, void>::store()  ???:0
 9 0x00000000005666a6 madness::archive::ArchiveImpl<madness::archive::BufferOutputArchive, std::vector<std::pair<madness::Key<3ul>, double>, std::allocator<std::pair<madness::Key<3ul>, double> > >, void>::wrap_store<madness::archive::BufferOutputArchive, void>()  ???:0
10 0x0000000000555034 madness::archive::operator&<madness::archive::BufferOutputArchive, std::vector<std::pair<madness::Key<3ul>, double>, std::allocator<std::pair<madness::Key<3ul>, double> > > >()  ???:0
11 0x000000000054537a madness::WorldGopInterface::concat0<std::pair<madness::Key<3ul>, double> >()  ???:0
12 0x0000000000535a95 madness::LoadBalanceDeux<3ul>::load_balance()  ???:0
13 0x0000000000514cb0 madness::SCF::initial_load_bal()  ???:0
14 0x0000000000437d9d main()  ???:0
15 0x0000000000022555 __libc_start_main()  ???:0
16 0x0000000000437129 _start()  ???:0
=================================
```

**Comment by fbischoff** [comment] 2024-10-15 13:44
I just realized the issue is already open. git bisect tells me its somewhere in commits 0386b7f5a7b0f30e03bd39e6adcbb80bbd91c5ac or c7e2673978583334a2a9b555477642ccdc601764.
@evaleev  @EricaCMitchell  : can you please run madness with 2 or more processes and make sure there is no segfault?

**Comment by evaleev** [comment] 2024-10-15 19:45
@fbischoff all tests in CI passed, and I assumed the minimal functionality worked ... is `moldft` not part of CI by default?

**Comment by EricaCMitchell** [comment] 2024-10-15 23:19
PR #553 has been merged to fix this.

For posterity, I was able to confirm that this fixed the problem on both Apple Silicon and Linux HPC.

**Closed by EricaCMitchell** 2024-10-15 23:19 UTC

**Comment by fbischoff** [comment] 2024-10-16 07:29
Great, seems to work now, thanks for the quick response!

Best,
Florian



------------------------------------------------------
Florian Bischoff
Humboldt-Universitaet zu Berlin, Institut fuer Chemie
Unter den Linden 6, 10099 Berlin
phone: +49-30-2093-82708
office: Brook-Taylor-Str 2, room 3'322
***@***.***
https://tinyurl.com/bischofflab
