### ISSUE TITLE
Rengineering of the TBB code -- Make it work by default

### ISSUE THREAD

**Issue by wsttiger** [m-a-d-n-e-s-s/madness#49] opened 2014-08-27 12:04 UTC
Autoconfigure/detect and use an old as fallback

**Comment by justusc** [comment] 2015-01-28 17:56
The barrier to this issue is a reliable TBB implementation on BG/Q (see issue #52).

**Comment by naromero77** [comment] 2015-02-14 20:16
I think we can move forward with this. We just need to agree on how long we should keep compatibility with the old taskq.

**Comment by justusc** [comment] 2015-02-14 20:36
Is TBB working out of the box now on BG/Q or do we have documentation on how to build it?

**Comment by naromero77** [comment] 2015-02-14 23:18
No and no. However, I will document how to build on the wiki soon. But to close this ticket, we all have to agree to make TBB the default. I am fine with it.

**Comment by jeffhammond** [comment] 2015-02-15 04:52
It's documented somewhere because I was able to do it on the first try with
my github fork.

Jeff

On Saturday, February 14, 2015, Nichols A. Romero <notifications@github.com>
wrote:

> No and no. However, I will document how to build on the wiki soon. But to
> close this ticket, we all have to agree to make TBB the default. I am fine
> with it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/49#issuecomment-74396311>
> .
>


-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by robertjharrison** [comment] 2015-02-15 09:58
TBB is now auto detected and this is how I build routinely.

The question of how long we keep the old stuff is harder.   IBM Power8 etc
are a looming concern and so I anticipate keeping it around until we have
confirmed TBB on that platform.

**Comment by jeffhammond** [comment] 2015-02-16 02:35
I know that Raf did PPC64 porting of TBB on a POWER7 Linux login node of BGQ before he moved to the compute partition, so it should be fine on POWER except for the little-endian switch associated with OpenPOWER.  I don't know if there's anything endian-specific in TBB, but it's important to run the test suite anyways.

It has been hard to get IBM employees interested in TBB due to it having the double-whammy of Intel copyright and GPL.  I can talk to some IBM customers about helping us with testing.

**Comment by naromero77** [comment] 2015-04-03 18:50
Can I close this issue? There were a seperate TBB on BG/Q issue which is now closed. I think the question is whether TBB is the default. I think all of us are in agreement that it should be. I don't know if that is the default behavior.

**Comment by naromero77** [comment] 2015-04-03 20:47
TBB is already the default.

**Closed by naromero77** 2015-04-03 20:47 UTC
Labels: dependencies
