### ISSUE TITLE
Compile fails at worldprofile.cc on Cray XE6

### ISSUE THREAD

**Issue by justusc** [m-a-d-n-e-s-s/madness#12] opened 2014-06-07 11:59 UTC
Google Code issue 36

Reported by padamson1975, Mar 16, 2012

I'm compiling on a Cray XE6 (raptor at AFRL DSRC) using GNU compilers and ACML. Compile fails on worldprofile.cc with the following:
```
CC -DHAVE_CONFIG_H   -I../../../include -I../../../src/lib  -I../../../src/apps -I../../../include   -std=c++0x -O3 -Wall -Wno-strict-aliasing -Wno-deprecated  -ffast-math -std=c++0x -march=native -MT worldprofile.o -MD -MP -MF .deps/worldprofile.Tpo -c -o worldprofile.o worldprofile.cc
In file included from ../../../src/lib/world/mpiar.h:41:0,
                 from worldprofile.cc:35:
../../../src/lib/world/vecar.h: In member function 'typename madness::enable_if<madness::is_serializable<T>, void>::type madness::archive::VectorInputArchive::load(T*, long int) const':
../../../src/lib/world/vecar.h:92:57: error: there are no arguments to 'memcpy' that depend on a template parameter, so a declaration of 'memcpy' must be available
../../../src/lib/world/vecar.h:92:57: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
worldprofile.cc: At global scope:
worldprofile.cc:320:17: warning: 'void madness::est_profile_overhead()' defined but not used
make[3]: *** [worldprofile.o] Error 1
make[3]: Leaving directory `/home/padamson/opt/madness/src/lib/world'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/padamson/opt/madness/src/lib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/padamson/opt/madness/src'
make: *** [all-recursive] Error 1
```
I checked out the code using cvs.

Thanks,
Paul Adamson

**Comment by naromero77** [comment] 2015-02-14 20:32
I am just going to close it. The issue is 3 years old and the user is probably not around to give us more information.

**Closed by naromero77** 2015-02-14 20:32 UTC
Labels: bug
