### ISSUE TITLE
debian mipsel build issues

### ISSUE THREAD

**Issue by aborrero** [m-a-d-n-e-s-s/madness#148] opened 2015-07-31 20:07 UTC
Hi!

madness recently joined the Debian archive. However, it seems to fail to build from source in the mipsel arch [0].

The issue seems to be this:
```
[...]
../../../src/madness/world/timers.h:151:2: error: #error cpu_relax is not implemented!
 #error cpu_relax is not implemented!
  ^
[...]
```
Do you know how to address the issue?

best regards.

[0] https://buildd.debian.org/status/fetch.php?pkg=madness&arch=mipsel&ver=0.10-1&stamp=1437866412

**Comment by robertjharrison** [comment] 2015-07-31 20:11
Super cool ... how did we get into debian?

Anyway definitely worth making this work.  Imagine

apt-get install madness

Scott ... could you please assist him?

**Comment by justusc** [comment] 2015-08-01 14:55
The issue arises because the compiler does not define `__x86_64__` or `__i386`. One of these two macros must be defined by the compiler so that the appropriate inline assembly is selected. In the case of cpu_relax(), the inline assembly is the same for x86_64 and i386. But for other parts of the MADNESS code, the assembly differs between the two.

Currently, cpu_relax only has implementation for x86_64, i386, BG/Q, and BG/P.

It may also be necessary to define various `__SSE__`, `__SSE2__`, etc. for SSE support, and/or `__AVX__` or `__AVX2__` for AVX  support.

**Comment by aborrero** [comment] 2015-08-01 17:43
Could it be possible to get an implementation of cpu_relax() for mipsel? Could we simply use `noop`?

**Comment by jeffhammond** [comment] 2015-08-01 17:45
I think I can roll a portable implementation of all the stuff that currently requires assembly using a combination of C++11 and various Linux-isms.  For example, cpu_relax can be mapped to nanosleep, for example.

Note that I do not have access to any MIPS platforms, but I can use my Parallela board at home to verify the generic build on ARM32.

Those that enjoy irony will appreciate that the Intel employee is doing this.

**Comment by justusc** [comment] 2015-08-02 01:36
As @jeffhammond said, we can probably implement a portable cpu_relax function, but other parts of the code may not be as easy. Specifically, the mtxm code in the tensor library. Others who know more may be able to answer that question better.

**Comment by jeffhammond** [comment] 2015-08-02 01:48
This should be fixed by https://github.com/m-a-d-n-e-s-s/madness/pull/150, assuming that it passes CI.

Note that I fixed more than was requested.  The cpu_relax() function is just the first thing you saw failing.  The atomic class was only implemented for x86 and Blue Gene.  I just wrote a C++11 implementation, which should be as portable as it gets.

**Comment by jeffhammond** [comment] 2015-08-02 01:52
@justusc We do not need to implement a portable mTxm because we already have a BLAS implementation of those functions that is used as a means of last resort.  If we happen to have broken it somehow, it is easy to fix.

And yes, mTxm using BLAS is not the best implementation, but until we have users that regularly platforms besides x86 and Blue Gene, it should not be a priority.  And MIPS is just about the lowest priority I can imagine - ARM and SPARC have a presence in HPC today, and we don't have any optimized support for those yet.

**Comment by justusc** [comment] 2015-08-02 01:54
@jeffhammond thank you for the clarification.

**Comment by mbanck** [comment] 2015-08-02 14:12
@jeffhammond the Travis CI for #150 is displayed as failed, is that expected?

I'm happy to pull in your changeset for Debian to see how it works on the mips autobuilders, but if it's a WIP currently I'll hold off a bit more until it's merged.

**Comment by justusc** [comment] 2015-08-02 14:13
@mbanck I checked the Travis CI output and it is definitely not working as intended.

**Comment by jeffhammond** [comment] 2015-08-02 14:47
Travis is not helping me figure out what's wrong. Can you help me
understand, Justus?

The cpu_relax fix is trivial so maybe we can pull that out of let the
Debian folks try just that.

On Sunday, August 2, 2015, Justus Calvin <notifications@github.com> wrote:

> @mbanck <https://github.com/mbanck> I checked the Travis CI output and it
> is definitely not working as intended.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/148#issuecomment-127027400>
> .
>


-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by justusc** [comment] 2015-08-02 14:58
The error is on line 47 of atomicint.h. The operator you intended to use was ">=".

**Comment by jeffhammond** [comment] 2015-08-02 15:40
I committed f679f8f5cb45fd43e038964f9e5f22d030321f8a to master to address the cpu_relax issue and nothing else.  Can the Debian folks please try with that?

It's not clear to me that the asm-nop solution is portable, in which case I will do some investigating and find the right asm for every arch.

**Comment by jeffhammond** [comment] 2015-08-02 15:42
Thanks @justusc.  I should have been more careful with that.  I committed the fix in ac67249.

**Comment by mbanck** [comment] 2015-08-03 22:12
@jeffhammond I pulled in f679f8f and it looks much better now, i.e. it builds everywhere:: https://buildd.debian.org/status/package.php?p=madness

Will take a look at testsuite failures next when I get to it.

**Comment by jeffhammond** [comment] 2015-08-03 23:11
@mbanck Cool!  Glad to hear it.  But do you have use OpenMPI as the MPI dependency for MADNESS?  I have much higher confidence in the correctness of MADNESS with MPI_THREAD_MULTIPLE if MPICH is used.

**Comment by mbanck** [comment] 2015-09-14 15:20
@jeffhammond right, I just noticed OpenMPI in Debian does not support MPI_THREAD_MULTIPLE when I tried to switch this on. I'll file an issue for the fact that it'd be nice if MADNESS figured out at configure time that it will crash on runtime if it is configured with --with-mpi-threads=multiple, but the MPI implementation does not provide that.

The main problem is that Open MPI is the default on most Debian architectures, but I will see about just using MPICH for MADNESS/MPQ3.

**Comment by jeffhammond** [comment] 2015-09-14 18:31
@mbanck I suppose we could detect OpenMPI as non-compliant with MPI_THREAD_MULTIPLE, but I'd prefer that users report this bug directly to them and shame them into supporting the MPI standard properly.

**Comment by mbanck** [comment] 2015-09-15 00:01
well, it's a matter of configuration - as I understand it the message has been mixed in the past (i.e., MPI_THREAD_MULTIPLE is either not safe, or lowers performance on single-thread runs). Plus Open MPI has been mostly unmaintained in the recent past in Debian. If you can point me to some (upstream?) documentation that clearly states whether MPI_THREAD_MULTIPLE is either ok or not ok on Open MPI right now, that would be very helpful

**Comment by jeffhammond** [comment] 2015-09-18 04:38
As long as https://github.com/open-mpi/ompi/issues/157 is open, the answer
is "not ok".

Why is Debian default to OpenMPI if it is unmaintained?  Why don't you use
MPICH by default?  I never had a single problem with MPICH on Debian.

Jeff

On Mon, Sep 14, 2015 at 8:01 PM, Michael Banck <notifications@github.com>
wrote:

> well, it's a matter of configuration - as I understand it the message has
> been mixed in the past (i.e., MPI_THREAD_MULTIPLE is either not safe, or
> lowers performance on single-thread runs). Plus Open MPI has been mostly
> unmaintained in the recent past in Debian. If you can point me to some
> (upstream?) documentation that clearly states whether MPI_THREAD_MULTIPLE
> is either ok or not ok on Open MPI right now, that would be very helpful
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/148#issuecomment-140236403>
> .
>



-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by jeffhammond** [comment] 2015-12-15 14:07
@hjelmn tells me that [Open-MPI](https://github.com/open-mpi/ompi) 2.0 will support `MPI_THREAD_MULTIPLE`.  I do not know what the release schedule for that version is, although there is a [2.x branch](https://github.com/open-mpi/ompi-release/tree/v2.x) in their release repo.

**Comment by jeffhammond** [comment] 2015-12-15 14:12
@mbanck Please let me know if this issue has been resolved from a Debian perspective so that I can close the issue.

**Comment by mbanck** [comment] 2015-12-16 21:27
@jeffhammond I'd say this can be closed.

**Closed** 2015-12-16 22:01 UTC
Labels: portability
