### ISSUE TITLE
Compile issues with mpi.h and Intel impi 4.1

### ISSUE THREAD

**Issue by calewis** [m-a-d-n-e-s-s/madness#124] opened 2015-05-21 13:48 UTC
Impi 4.1 fails to compile world due to it requiring mpi.h being included before stdio.h.  The issue specifically has to do with mpi.h defining SEEK_SET and other macros that are also defined in stdio.h.  

It looks like this might have been an issue before since in safempi.h there are the following commented out lines:
    //#ifdef SEEK_SET
    //#undef SEEK_SET
    //#endif
    //#ifdef SEEK_CUR
    //#undef SEEK_CUR
    //#endif
    //#ifdef SEEK_END
    //#undef SEEK_END
    //#endif

which may have been a work around for this issue.

**Comment by jeffhammond** [comment] 2015-05-27 18:14
CPPFLAGS+="-DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX" takes care of this issue with MPICH, MVAPICH, Intel MPI, Cray MPI, Blue Gene MPI, and Open MPI.  As we only use the C bindings, we should define these by default.

**Comment by justusc** [comment] 2015-05-27 18:48
Why close the issue when it has not been addressed?

**Comment by jeffhammond** [comment] 2015-05-27 22:33
My response fully addressed the problem.  This is not a bug in MADNESS but rather the MPI standard.  It was fixed in MPI-3 (the C++ bindings were deleted) but is not implemented by anyone (i.e. implementers have kept their MPI-2 C++ support for backwards compatibility).

**Closed** 2015-05-28 01:07 UTC

**Comment by justusc** [comment] 2015-05-28 03:14
That is what I did. Thanks again.
