### ISSUE TITLE
Trouble building tensor library

### ISSUE THREAD

**Issue by wsttiger** [m-a-d-n-e-s-s/madness#158] opened 2015-09-21 18:14 UTC
I'm on a Haswell Cray box, and trying to build the tensor directory .... and I encounter the following error:

[wsthornton@lired tensor]$ mpiicpc -DHAVE_CONFIG_H -I../../../src -I../../../src -I../../../src/apps -DMPICH_SKIP_MPICXX=1 -DOMPI_SKIP_MPICXX=1 -std=c++11 -O3 -Wall -diag-disable remark,279,654,1125 -ip -no-prec-div -mkl=sequential -ansi -xHOST -MT mtxmq.lo -MD -MP -MF .deps/mtxmq.Tpo -c mtxmq.cc -o mtxmq.o
/tmp/icpcTrdofPas_.s: Assembler messages:
/tmp/icpcTrdofPas_.s:699: Error: suffix or operands invalid for `vbroadcastsd'
/tmp/icpcTrdofPas_.s:701: Error: suffix or operands invalid for `vbroadcastsd'
/tmp/icpcTrdofPas_.s:736: Error: suffix or operands invalid for `vbroadcastsd'
/tmp/icpcTrdofPas_.s:738: Error: suffix or operands invalid for `vbroadcastsd'
/tmp/icpcTrdofPas_.s:839: Error: suffix or operands invalid for `vbroadcastsd'
/tmp/icpcTrdofPas_.s:872: Error: suffix or operands invalid for `vbroadcastsd'

**Comment by robertjharrison** [comment] 2015-09-21 18:38
Odd.  It compiles on my haswell laptop, so perhaps the default compilation
options have changed with the more recent icpc?

Of course you are just using the sse source and not the avx or even avx2
versions.

Try replacing your mtxmq.cc with the attached one and also add these
compilation options (but don't check it into git).

 CXXFLAGS="-mavx -mfma -mavx2 -ggdb -DAVX_MTXMQ_TEST



On Mon, Sep 21, 2015 at 2:14 PM, wsttiger <notifications@github.com> wrote:

> I'm on a Haswell Cray box, and trying to build the tensor directory ....
> and I encounter the following error:
>
> [wsthornton@lired tensor]$ mpiicpc -DHAVE_CONFIG_H -I../../../src
> -I../../../src -I../../../src/apps -DMPICH_SKIP_MPICXX=1
> -DOMPI_SKIP_MPICXX=1 -std=c++11 -O3 -Wall -diag-disable remark,279,654,1125
> -ip -no-prec-div -mkl=sequential -ansi -xHOST -MT mtxmq.lo -MD -MP -MF
> .deps/mtxmq.Tpo -c mtxmq.cc -o mtxmq.o
> /tmp/icpcTrdofPas_.s: Assembler messages:
> /tmp/icpcTrdofPas_.s:699: Error: suffix or operands invalid for
> vbroadcastsd'
> /tmp/icpcTrdofPas_.s:701: Error: suffix or operands invalid for
> vbroadcastsd'
> /tmp/icpcTrdofPas_.s:736: Error: suffix or operands invalid for
> vbroadcastsd'
> /tmp/icpcTrdofPas_.s:738: Error: suffix or operands invalid for
> vbroadcastsd'
> /tmp/icpcTrdofPas_.s:839: Error: suffix or operands invalid for
> vbroadcastsd'
> /tmp/icpcTrdofPas_.s:872: Error: suffix or operands invalid for
> vbroadcastsd'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/158>.
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by wsttiger** [comment] 2015-09-21 19:19
There is no attached file that I see.

**Comment by justusc** [comment] 2015-09-21 19:20
You cannot attach files when replying to messages from GH.

**Comment by jeffhammond** [comment] 2015-09-30 03:14
What version of toolchain?

icpc --version

If Cray XC, you must use MPICXX=CC not mpiicpc. You using CS box or
something?

On Monday, September 21, 2015, Justus Calvin <notifications@github.com>
wrote:

> You cannot attach files when replying to messages from GH.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/158#issuecomment-142083279>
> .
>


-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by robertjharrison** [comment] 2015-09-30 15:05
I am now seeing this problem with Intel 15.0.1 on Haswell.

Compiling the stock mtxmq.cc with

libtool: compile:  mpiicpc -DHAVE_CONFIG_H -I../../../src -I../../../src
-I../../../src/apps -I/gpfs/home/rjh/install-icc-15.0.1/include
-I/gpfs/home/rjh/install-icc-15.0.1/include -DMPICH_SKIP_MPICXX=1
-DOMPI_SKIP_MPICXX=1 -g -DAVX_MTXMQ_TEST -std=c++11 -O3 -Wall -diag-disable
remark,279,654,1125 -ip -no-prec-div -mkl=sequential -ansi -xHOST -MT
mtxmq.lo -MD -MP -MF .deps/mtxmq.Tpo -c mtxmq.cc  -fPIC -DPIC -o
.libs/mtxmq.o

produces

/tmp/icpcHIdGo8as_.s: Assembler messages:
/tmp/icpcHIdGo8as_.s:1978: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/icpcHIdGo8as_.s:1987: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/icpcHIdGo8as_.s:1996: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/icpcHIdGo8as_.s:2005: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/icpcHIdGo8as_.s:2014: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/icpcHIdGo8as_.s:4091: Error: suffix or operands invalid for
`vbroadcastsd'
/tmp/icpcHIdGo8as_.s:4097: Error: suffix or operands invalid for
`vbroadcastsd'
/tmp/icpcHIdGo8as_.s:4177: Error: suffix or operands invalid for
`vbroadcastsd'
/tmp/icpcHIdGo8as_.s:4183: Error: suffix or operands invalid for
`vbroadcastsd'
/tmp/icpcHIdGo8as_.s:4421: Error: suffix or operands invalid for
`vbroadcastsd'
/tmp/icpcHIdGo8as_.s:4499: Error: suffix or operands invalid for
`vbroadcastsd'

The instructions vpcmpeqd and vbroadcastsd are not in any of our code and
are presumably compiler generated.

If I remove the -xHOST option, the compilation succeeds.



On Tue, Sep 29, 2015 at 11:14 PM, Jeff Hammond <notifications@github.com>
wrote:

> What version of toolchain?
>
> icpc --version
>
> If Cray XC, you must use MPICXX=CC not mpiicpc. You using CS box or
> something?
>
> On Monday, September 21, 2015, Justus Calvin <notifications@github.com>
> wrote:
>
> > You cannot attach files when replying to messages from GH.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/m-a-d-n-e-s-s/madness/issues/158#issuecomment-142083279
> >
> > .
> >
>
>
> --
> Jeff Hammond
> jeff.science@gmail.com
> http://jeffhammond.github.io/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/158#issuecomment-144270186>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by jeffhammond** [comment] 2015-09-30 17:50
This is almost certainly related to the Mac toolchain and not the Intel compiler.  I frequently look to StackOverflow for workarounds to stuff like this.  Frequently, the solutions involve using the official Xcode clang as the linker.

**Comment by robertjharrison** [comment] 2015-09-30 18:30
This is on linux


On Wed, Sep 30, 2015 at 1:50 PM, Jeff Hammond <notifications@github.com>
wrote:

> This is almost certainly related to the Mac toolchain and not the Intel
> compiler. I frequently look to StackOverflow for workarounds to stuff like
> this. Frequently, the solutions involve using the official Xcode clang as
> the linker.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/158#issuecomment-144489451>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by robertjharrison** [comment] 2015-09-30 18:31
latest centos

On Wed, Sep 30, 2015 at 2:30 PM, Robert Harrison <rjharrison@gmail.com>
wrote:

> This is on linux
>
>
> On Wed, Sep 30, 2015 at 1:50 PM, Jeff Hammond <notifications@github.com>
> wrote:
>
>> This is almost certainly related to the Mac toolchain and not the Intel
>> compiler. I frequently look to StackOverflow for workarounds to stuff like
>> this. Frequently, the solutions involve using the official Xcode clang as
>> the linker.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/m-a-d-n-e-s-s/madness/issues/158#issuecomment-144489451>
>> .
>>
>
>
>
> --
> Robert J. Harrison
> tel:  865-272-9262
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by jeffhammond** [comment] 2015-10-01 03:05
Latest CentOS is how many years behind Fedora? What version of GCC and
binutils?

On Wednesday, September 30, 2015, robertjharrison <notifications@github.com>
wrote:

> latest centos
>
> On Wed, Sep 30, 2015 at 2:30 PM, Robert Harrison <rjharrison@gmail.com
> <javascript:_e(%7B%7D,'cvml','rjharrison@gmail.com');>>
> wrote:
>
> > This is on linux
> >
> >
> > On Wed, Sep 30, 2015 at 1:50 PM, Jeff Hammond <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> >> This is almost certainly related to the Mac toolchain and not the Intel
> >> compiler. I frequently look to StackOverflow for workarounds to stuff
> like
> >> this. Frequently, the solutions involve using the official Xcode clang
> as
> >> the linker.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/m-a-d-n-e-s-s/madness/issues/158#issuecomment-144489451
> >
> >> .
> >>
> >
> >
> >
> > --
> > Robert J. Harrison
> > tel: 865-272-9262
> >
>
>
>
> --
> Robert J. Harrison
> tel: 865-272-9262
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/158#issuecomment-144500487>
> .
>


-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by justusc** [comment] 2015-10-01 11:35
Check which version of the GCC standard library the Intel compiler is using. By default, it uses `gcc` and `g++` in your path, which typically points to the system compiler. As @jeffhammond pointed out, this is an ancient compiler and should not be used. You can specify the gcc standard library with the `-gcc-name=/path/to/new/gcc` and `-gxx-name=/path/to/new/g++` command line arguments. Also, be aware that the Intel compiler does not fully support the latest GCC compilers either. GCC 4.9.2 works. I am not sure if/which GCC 5 versions work.

**Comment by robertjharrison** [comment] 2015-10-03 21:05
Using 4.9.2 that trick did not fix things ... perhaps it is picking other
tools/headers?

bash-4.1$ mpiicpc -DHAVE_CONFIG_H -I../../../src -I../../../src
-I../../../src/apps -I/gpfs/home/rjh/install-icc-15.0.1/include -I/gpfs/ho\
me/rjh/install-icc-15.0.1/include -DMPICH_SKIP_MPICXX=1
-DOMPI_SKIP_MPICXX=1 -g -DAVX_MTXMQ_TEST -std=c++11 -O3 -Wall -diag-disable
remark\
,279,654,1125 -ip -no-prec-div -mkl=sequential -ansi -xHOST -MT mtxmq.lo
-MD -MP -MF .deps/mtxmq.Tpo -c mtxmq.cc  -fPIC -DPIC -o .libs/mtx\
mq.o -gcc-name=`which gcc` -gxx-name=`which g++`
/tmp/icpcYqD9Mnas_.s: Assembler messages:
/tmp/icpcYqD9Mnas_.s:1988: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/icpcYqD9Mnas_.s:1997: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/icpcYqD9Mnas_.s:2006: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/icpcYqD9Mnas_.s:2015: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/icpcYqD9Mnas_.s:2024: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/icpcYqD9Mnas_.s:4101: Error: suffix or operands invalid for
`vbroadcastsd'
/tmp/icpcYqD9Mnas_.s:4107: Error: suffix or operands invalid for
`vbroadcastsd'
/tmp/icpcYqD9Mnas_.s:4187: Error: suffix or operands invalid for
`vbroadcastsd'
/tmp/icpcYqD9Mnas_.s:4193: Error: suffix or operands invalid for
`vbroadcastsd'
/tmp/icpcYqD9Mnas_.s:4431: Error: suffix or operands invalid for
`vbroadcastsd'
/tmp/icpcYqD9Mnas_.s:4509: Error: suffix or operands invalid for
`vbroadcastsd'
bash-4.1$ which gcc
/gpfs/software/gcc-4.9.2/bin/gcc
bash-4.1$ which g++
/gpfs/software/gcc-4.9.2/bin/g++



On Thu, Oct 1, 2015 at 7:35 AM, Justus Calvin <notifications@github.com>
wrote:

> Check which version of the GCC standard library the Intel compiler is
> using. By default, it uses gcc and g++ in your path, which typically
> points to the system compiler. As @jeffhammond
> <https://github.com/jeffhammond> pointed out, this is an ancient compiler
> and should not be used. You can specify the gcc standard library with the
> -gcc-name=/path/to/new/gcc and -gxx-name=/path/to/new/g++ command line
> arguments. Also, be aware that the Intel compiler does not fully support
> the latest GCC compilers either. GCC 4.9.2 works. I am not sure if/which
> GCC 5 versions work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/158#issuecomment-144703187>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by justusc** [comment] 2015-10-03 22:58
One possible explanation for the error is that one of the assembly instructions is being mapped to `vpcmpeqd` and `vbroadcastsd`.

I do not think
```
-gcc-name=`which gcc` -gxx-name=`which g++`
```
differs from the default behavior. If `which g++` returns the path to GCC 4.9.2, then I believe icpc will use the correct compiler. You only need to ensure `which g++` returns the correct compiler (not `/usr/bin/g++`) or that you specify it with the above command line options.

It probably will not make a difference, but you are passing both `-std=c++11` and `-ansi`. You should only use `-std=c++11`.

**Comment by robertjharrison** [comment] 2015-10-03 23:47
I think the problem is not the compiler version but binutils.  CENTOS is at
2.20 but it seems that 2.25 is the latest (which is where my ubuntu laptop
is at)

Ugh.



On Sat, Oct 3, 2015 at 6:58 PM, Justus Calvin <notifications@github.com>
wrote:

> One possible explanation for the error is that one of the assembly
> instructions is being mapped to vpcmpeqd and vbroadcastsd.
>
> I do not think
>
> -gcc-name=`which gcc` -gxx-name=`which g++`
>
> differs from the default behavior. If which g++ returns the path to GCC
> 4.9.2, then I believe icpc will use the correct compiler. You only need to
> ensure which g++ returns the correct compiler (not /usr/bin/g++) or that
> you specify it with the above command line options.
>
> It probably will not make a difference, but you are passing both
> -std=c++11 and -ansi. You should only use -std=c++11.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/158#issuecomment-145296309>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by robertjharrison** [comment] 2015-10-04 00:35
Yep, that fixed it.

Scott ... binutils-2.25 is now in /gfps/software

On Sat, Oct 3, 2015 at 7:47 PM, Robert Harrison <rjharrison@gmail.com>
wrote:

> I think the problem is not the compiler version but binutils.  CENTOS is
> at 2.20 but it seems that 2.25 is the latest (which is where my ubuntu
> laptop is at)
>
> Ugh.
>
>
>
> On Sat, Oct 3, 2015 at 6:58 PM, Justus Calvin <notifications@github.com>
> wrote:
>
>> One possible explanation for the error is that one of the assembly
>> instructions is being mapped to vpcmpeqd and vbroadcastsd.
>>
>> I do not think
>>
>> -gcc-name=`which gcc` -gxx-name=`which g++`
>>
>> differs from the default behavior. If which g++ returns the path to GCC
>> 4.9.2, then I believe icpc will use the correct compiler. You only need to
>> ensure which g++ returns the correct compiler (not /usr/bin/g++) or that
>> you specify it with the above command line options.
>>
>> It probably will not make a difference, but you are passing both
>> -std=c++11 and -ansi. You should only use -std=c++11.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/m-a-d-n-e-s-s/madness/issues/158#issuecomment-145296309>
>> .
>>
>
>
>
> --
> Robert J. Harrison
> tel:  865-272-9262
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by jeffhammond** [comment] 2016-09-07 23:02
I am going to close this issue.

I too have to build binutils from source to support Haswell ISA with CentoOS 6.

**Closed by jeffhammond** 2016-09-07 23:02 UTC
